### ISSUE TITLE
PKCS1 padding not as long as expected

### ISSUE THREAD

**Issue by eriknellessen** [licel/jcardsim#82] opened 2016-04-12 16:26 UTC
I am working on executing the OpenPGP Java Card applet on an android smartphone using jCardSim ([jcardsim-3.0.4-SNAPSHOT.jar](https://github.com/licel/jcardsim/blob/master/jcardsim-3.0.4-SNAPSHOT.jar)).

As you can see in [this thread](https://lists.gnupg.org/pipermail/gnupg-devel/2016-April/030965.html), creating signatures does not work yet. The reason for this is, that the signatures created in the applet are not padded as in the OpenPGP card standard. The padding is part of jCardSim, which, I guess, uses BouncyCastle to implement it.

I could not find any hint in the PKCS1 standard, telling me that the hashes always have to be padded to the full key length. This would mean, that both behaviors are correct according to the standard, but only one behavior is accepted in OpenPGP. Anyhow, I am not very familiar with this standard and might have missed something. Maybe you know more about this.

Do you think it is possible, that jCardSim influences the padding? Or can this only be (if at all) a BouncyCastle problem?

Any kind of help would be appreciated!

**Comment by licel** [comment] 2016-04-13 07:27
Hi, Erik! Thank you for your report. Most likely you are right, and the problem is in the padding. Which version of OpenPGP Java Card Applet do you use?

Best Regards,
Mikhail Dudarev

**Comment by eriknellessen** [comment] 2016-04-13 07:46
I am using the latest version from [here](https://sourceforge.net/projects/javacardopenpgp/), i.e. revision 13.

I also tried the [ykneo-opengpg applet](https://github.com/Yubico/ykneo-openpgp), which resulted in the same problem. As you can see [here](https://github.com/Yubico/ykneo-openpgp/blob/master/applet/src/openpgpcard/OpenPGPApplet.java#L631), an object called "cipher" is used to compute the signature. This object is initialized [here](https://github.com/Yubico/ykneo-openpgp/blob/master/applet/src/openpgpcard/OpenPGPApplet.java#L203), using the [Cipher](https://jcardsim.org/jcardsim/javacardx/crypto/Cipher.html) class (which in my case is implemented by jCardSim).

My guess is, that this Cipher class behaves differently (concerning the PKCS1 padding) in jCardSim than in the original Java card.

**Comment by licel** [comment] 2016-04-13 08:14
Now it is clear, it seems that the problem is connected to the implementation of Cipher in jCardSim. We will fix that asap.

**Comment by licel** [comment] 2016-04-13 08:15
I think it would be a great idea to make integration tests for jCardSim/OpenPGP Java Card Applet and gpg.

**Comment by licel** [comment] 2016-04-13 12:44
I have attached a new build jcardsim-3.0.4-SNAPSHOT.jar. Could you please try it out and us know if it helps?

[jcardsim-3.0.4-SNAPSHOT.jar.zip](https://github.com/licel/jcardsim/files/217084/jcardsim-3.0.4-SNAPSHOT.jar.zip)

**Comment by eriknellessen** [comment] 2016-04-13 15:15
If I use the new library file for building, the following error message is returned:
> 
-dex:
      [dex] input: prefix/Android/bin/classes
      [dex] input: prefix/Android/libs/jcardsim-3.0.4-SNAPSHOT.jar
      [dex] Pre-Dexing prefix/Android/libs/jcardsim-3.0.4-SNAPSHOT.jar -> jcardsim-3.0.4-SNAPSHOT-6755a889e99e252640a268c4ea29899d.jar
       [dx] 
       [dx] trouble processing "java/io/IOException.class":
       [dx] 
       [dx] Ill-advised or mistaken usage of a core class (java.* or javax.*)
       [dx] when not building a core library.
       [dx] 
       [dx] This is often due to inadvertently including a core library file
       [dx] in your application's project, when using an IDE (such as
       [dx] Eclipse). If you are sure you're not intentionally defining a
       [dx] core class, then this is the most likely explanation of what's
       [dx] going on.
       [dx] 
       [dx] However, you might actually be trying to define a class in a core
       [dx] namespace, the source of which you may have taken, for example,
       [dx] from a non-Android virtual machine project. This will most
       [dx] assuredly not work. At a minimum, it jeopardizes the
       [dx] compatibility of your app with future versions of the platform.
       [dx] It is also often of questionable legality.
       [dx] 
       [dx] If you really intend to build a core library -- which is only
       [dx] appropriate as part of creating a full virtual machine
       [dx] distribution, as opposed to compiling an application -- then use
       [dx] the "--core-library" option to suppress this error message.
       [dx] 
       [dx] If you go ahead and use "--core-library" but are in fact
       [dx] building an application, then be forewarned that your application
       [dx] will still fail to build or run, at some point. Please be
       [dx] prepared for angry customers who find, for example, that your
       [dx] application ceases to function once they upgrade their operating
       [dx] system. You will be to blame for this problem.
       [dx] 
       [dx] If you are legitimately using some code that happens to be in a
       [dx] core package, then the easiest safe alternative you have is to
       [dx] repackage that code. That is, move the classes in question into
       [dx] your own package namespace. This means that they will never be in
       [dx] conflict with core system classes. JarJar is a tool that may help
       [dx] you in this endeavor. If you find that you cannot do this, then
       [dx] that is an indication that the path you are on will ultimately
       [dx] lead to pain, suffering, grief, and lamentation.
       [dx] 
       [dx] 1 error; aborting

> BUILD FAILED

**Comment by licel** [comment] 2016-04-13 16:23
Sorry for inconvenience. I have built the new version of library without base java classes (see attach).
[jcardsim-3.0.4-SNAPSHOT.jar.zip](https://github.com/licel/jcardsim/files/217515/jcardsim-3.0.4-SNAPSHOT.jar.zip)

**Comment by eriknellessen** [comment] 2016-04-13 16:55
With that version, compiling works for me. But I get the following runtime error:
>E/AndroidRuntime(10253): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bouncycastle/util/encoders/Hex;
E/AndroidRuntime(10253):        at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:96)
E/AndroidRuntime(10253):        at com.licel.jcardsim.base.Simulator.<init>(Simulator.java:81)

**Comment by licel** [comment] 2016-04-13 17:18
Ohhh, I missed (see attach)
[jcardsim-3.0.4-SNAPSHOT.jar.zip](https://github.com/licel/jcardsim/files/217621/jcardsim-3.0.4-SNAPSHOT.jar.zip)

**Comment by eriknellessen** [comment] 2016-04-13 17:54
The runtime error does not appear anymore.

But now, the PIN retry counters are all set to zero, so I can not authenticate. That is why I still can not generate a key to test, if the original problem vanished with the new version of jCardSim.

Output of gpg2 --card-status (with the newest jCardSim version you posted):
>Application ID ...: D2760001240102000000000000010000
Version ..........: 2.0
Manufacturer .....: test card
Serial number ....: 00000001
Name of cardholder: [not set]
Language prefs ...: [not set]
Sex ..............: unspecified
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 0 0 0
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]

With the original jCardSim version, the output is:
>Application ID ...: D2760001240102000000000000010000
Version ..........: 2.0
Manufacturer .....: test card
Serial number ....: 00000001
Name of cardholder: [not set]
Language prefs ...: [not set]
Sex ..............: unspecified
URL of public key : [not set]
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 3 3
Signature counter : 0
Signature key ....: [none]
Encryption key....: [none]
Authentication key: [none]
General key info..: [none]

**Comment by licel** [comment] 2016-04-13 19:05
Ok. Most likely the problem is in the developer build. Our team will check the compatibility with OpenPGP JavaCard Applet tomorrow. Thanks for the information!

**Comment by licel** [comment] 2016-04-14 13:07
[jcardsim-3.0.4-SNAPSHOT.jar.zip](https://github.com/licel/jcardsim/files/219164/jcardsim-3.0.4-SNAPSHOT.jar.zip)
We have fixed the issue with OwnerPin, please check out the new version.

**Comment by eriknellessen** [comment] 2016-04-14 13:31
With that version, the padding had the expected length. I was able to generate a key on the card. So from my point of view, this issue can be closed.

Thank you very much!

**Comment by licel** [comment] 2016-04-14 13:47
We are very happy hearing that the the problem was resolved. We will close the issue once changes and unit-tests are committed to the repository.  Thank you for finding the issue and your help in resolving it.

**Closed** 2016-04-15 10:42 UTC
Labels: bug, Priority-High
